### ISSUE TITLE
Unit tests won't work with `AuthorizationGuard` enabled

### ISSUE THREAD

**Issue by marcin-dlubakowski** [Lokicoule/nestjs-cognito#932] opened 2024-04-18 16:59 UTC
**Describe the bug**
Controllers that utilize `AuthorizationGuard` are impossible to unit test - they will fail due to missing Cognito dependencies.
I think this is due to the fact that `AuthorizationGuard` is not real class, and the `overrideGuard` method is unable to mock it. This causes tests to try loading the entire module, effectively breaking everything.
I have created an [example repo](https://github.com/marcin-dlubakowski/nestjs-cognito-unit-testing) which highlights this issue.

**To Reproduce**
1. See file in this repository: https://github.com/marcin-dlubakowski/nestjs-cognito-unit-testing/blob/main/src/qweasd/qweasd.controller.spec.ts
2. If you run `npm run test ` in this repo, you will be greeted with failed test:
```> cognito-auth-unit-testing@0.0.1 test
> jest

 PASS  src/app.controller.spec.ts
 FAIL  src/qweasd/qweasd.controller.spec.ts
  ● QweasdController › /qweasd › should return "Hello World!"

    Nest can't resolve dependencies of the 308c31108bc06f1613772 (?, Reflector). Please make sure that the argument "COGNITO_JWT_VERIFIER_INSTANCE_TOKEN" at index [0] is available in the RootTestModule context.

    Potential solutions:
    - Is RootTestModule a valid NestJS module?
    - If "COGNITO_JWT_VERIFIER_INSTANCE_TOKEN" is a provider, is it part of the current RootTestModule?
    - If "COGNITO_JWT_VERIFIER_INSTANCE_TOKEN" is exported from a separate @Module, is that module imported within RootTestModule?
      @Module({
        imports: [ /* the Module containing "COGNITO_JWT_VERIFIER_INSTANCE_TOKEN" */ ]
      })

       7 |
       8 |   beforeEach(async () => {
    >  9 |     const app: TestingModule = await Test.createTestingModule({
         |                                ^
      10 |       controllers: [QweasdController],
      11 |     })
      12 |       .overrideGuard(AuthorizationGuard)

      at TestingInjector.lookupComponentInParentModules (../node_modules/@nestjs/core/injector/injector.js:254:19)
      at TestingInjector.resolveComponentInstance (../node_modules/@nestjs/core/injector/injector.js:207:33)
      at TestingInjector.resolveComponentInstance (../node_modules/@nestjs/testing/testing-injector.js:19:45)
      at resolveParam (../node_modules/@nestjs/core/injector/injector.js:128:38)
          at async Promise.all (index 0)
      at TestingInjector.resolveConstructorParams (../node_modules/@nestjs/core/injector/injector.js:143:27)
      at TestingInjector.loadInstance (../node_modules/@nestjs/core/injector/injector.js:70:13)
      at TestingInjector.loadInjectable (../node_modules/@nestjs/core/injector/injector.js:93:9)
      at ../node_modules/@nestjs/core/injector/instance-loader.js:80:13
          at async Promise.all (index 0)
      at TestingInstanceLoader.createInstancesOfInjectables (../node_modules/@nestjs/core/injector/instance-loader.js:79:9)
      at ../node_modules/@nestjs/core/injector/instance-loader.js:41:13
          at async Promise.all (index 1)
      at TestingInstanceLoader.createInstances (../node_modules/@nestjs/core/injector/instance-loader.js:39:9)
      at TestingInstanceLoader.createInstancesOfDependencies (../node_modules/@nestjs/core/injector/instance-loader.js:22:13)
      at TestingInstanceLoader.createInstancesOfDependencies (../node_modules/@nestjs/testing/testing-instance-loader.js:9:9)
      at TestingModuleBuilder.createInstancesOfDependencies (../node_modules/@nestjs/testing/testing-module.builder.js:118:9)
      at TestingModuleBuilder.compile (../node_modules/@nestjs/testing/testing-module.builder.js:74:9)
      at Object.<anonymous> (qweasd/qweasd.controller.spec.ts:9:32)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.578 s, estimated 2 s
Ran all test suites.```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by Lokicoule** [comment] 2024-04-18 19:58
Hi @marcin-dlubakowski,

Thank you for sharing the example repository. I was able to investigate the issue you were having easily.

Regarding the `app.controller.spec.ts` file, it seems to be functioning correctly. However, you forgot to utilize the `AuthenticationGuard` which means that it won't work properly if you add the guard to the controller.

As for the `qweasd.controller.spec.ts` file, the problem is that you need to import the `CognitoAuthModule` (with fake data) to register the `COGNITO_JWT_VERIFIER_INSTANCE_TOKEN` into the NestJS DI container. This should solve the issue you were facing. 

If you have any further questions, please let me know.

**Comment by Lokicoule** [comment] 2024-05-01 11:47
Hey @marcin-dlubakowski,

I closed this issue but don't hesitate to open it again!

Have a nice day!

**Closed** 2024-05-01 11:48 UTC
